name: Publish application on Tagged Release
run-name: ${{ github.actor }} is running ${{ github.workflow }}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.401

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Build for Windows
      - name: Build Windows Executable
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -r win-x64 --self-contained -o ./publish/windows/

      # Build for Linux
      - name: Build Linux Executable
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -r linux-x64 --self-contained -o ./publish/linux/

      # Build for macOS
      - name: Build macOS Executable
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -r osx-x64 --self-contained -o ./publish/macos/

      # Zip the executables
      - name: Compress Windows Executable
        run: zip -j Chirp-Windows-x64.zip ./publish/windows/Chirp.Razor.exe

      - name: Compress Linux Executable
        run: zip -j Chirp-Linux-x64.zip ./publish/linux/Chirp.Razor

      - name: Compress macOS Executable
        run: zip -j Chirp-macOS-x64.zip ./publish/macos/Chirp.Razor

      # Create a GitHub Release and upload the zips
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Chirp-Windows-x64.zip
            Chirp-Linux-x64.zip
            Chirp-macOS-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
