name: Build and test application
run-name: ${{ github.actor }} is running ${{ github.workflow }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.401

      - name: Install Playwright CLI for .NET
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

      - name: Install Playwright Browsers for .NET
        run: dotnet playwright install

      - name: Run Playwright Tests
        run: dotnet test --no-build --verbosity normal
