name: Build and test application
run-name: ${{ github.actor }} is running ${{ github.workflow }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.401

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Playwright CLI for .NET
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Add .NET Tools to PATH
        run: echo "##[add-path]$HOME/.dotnet/tools"

      - name: Install Playwright Browsers
        run: dotnet playwright install --with-deps

      - name: Build the project
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
