name: Build and test application
run-name: ${{ github.actor }} is running ${{ github.workflow }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.401

      - name: Install Playwright CLI for .NET
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Install Playwright Browsers
        run: playwright install --force

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

      - name: Run Playwright Tests
        run: dotnet test --no-build --verbosity normal
