name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup31razor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build src/Chirp.Razor/ --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Chirp.Razor/ -c Release -o ${{github.workspace}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_91650D9696DD41F8AA01556401266C4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_71C6F0E914BB4F7EB76E4FD15624CC19 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_498D6E78F6214C67B8FF41D70DB72ED8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup31razor'
          slot-name: 'Production'
          package: ${{github.workspace}}/myapp
